require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/cost_centers", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # CostCenter. As you add validations to CostCenter, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      CostCenter.create! valid_attributes
      get cost_centers_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      cost_center = CostCenter.create! valid_attributes
      get cost_center_url(cost_center)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_cost_center_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      cost_center = CostCenter.create! valid_attributes
      get edit_cost_center_url(cost_center)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CostCenter" do
        expect {
          post cost_centers_url, params: { cost_center: valid_attributes }
        }.to change(CostCenter, :count).by(1)
      end

      it "redirects to the created cost_center" do
        post cost_centers_url, params: { cost_center: valid_attributes }
        expect(response).to redirect_to(cost_center_url(CostCenter.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new CostCenter" do
        expect {
          post cost_centers_url, params: { cost_center: invalid_attributes }
        }.to change(CostCenter, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post cost_centers_url, params: { cost_center: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested cost_center" do
        cost_center = CostCenter.create! valid_attributes
        patch cost_center_url(cost_center), params: { cost_center: new_attributes }
        cost_center.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the cost_center" do
        cost_center = CostCenter.create! valid_attributes
        patch cost_center_url(cost_center), params: { cost_center: new_attributes }
        cost_center.reload
        expect(response).to redirect_to(cost_center_url(cost_center))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        cost_center = CostCenter.create! valid_attributes
        patch cost_center_url(cost_center), params: { cost_center: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested cost_center" do
      cost_center = CostCenter.create! valid_attributes
      expect {
        delete cost_center_url(cost_center)
      }.to change(CostCenter, :count).by(-1)
    end

    it "redirects to the cost_centers list" do
      cost_center = CostCenter.create! valid_attributes
      delete cost_center_url(cost_center)
      expect(response).to redirect_to(cost_centers_url)
    end
  end
end
