require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/orientation_manuals", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # OrientationManual. As you add validations to OrientationManual, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      OrientationManual.create! valid_attributes
      get orientation_manuals_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      orientation_manual = OrientationManual.create! valid_attributes
      get orientation_manual_url(orientation_manual)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_orientation_manual_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      orientation_manual = OrientationManual.create! valid_attributes
      get edit_orientation_manual_url(orientation_manual)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new OrientationManual" do
        expect {
          post orientation_manuals_url, params: { orientation_manual: valid_attributes }
        }.to change(OrientationManual, :count).by(1)
      end

      it "redirects to the created orientation_manual" do
        post orientation_manuals_url, params: { orientation_manual: valid_attributes }
        expect(response).to redirect_to(orientation_manual_url(OrientationManual.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new OrientationManual" do
        expect {
          post orientation_manuals_url, params: { orientation_manual: invalid_attributes }
        }.to change(OrientationManual, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post orientation_manuals_url, params: { orientation_manual: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested orientation_manual" do
        orientation_manual = OrientationManual.create! valid_attributes
        patch orientation_manual_url(orientation_manual), params: { orientation_manual: new_attributes }
        orientation_manual.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the orientation_manual" do
        orientation_manual = OrientationManual.create! valid_attributes
        patch orientation_manual_url(orientation_manual), params: { orientation_manual: new_attributes }
        orientation_manual.reload
        expect(response).to redirect_to(orientation_manual_url(orientation_manual))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        orientation_manual = OrientationManual.create! valid_attributes
        patch orientation_manual_url(orientation_manual), params: { orientation_manual: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested orientation_manual" do
      orientation_manual = OrientationManual.create! valid_attributes
      expect {
        delete orientation_manual_url(orientation_manual)
      }.to change(OrientationManual, :count).by(-1)
    end

    it "redirects to the orientation_manuals list" do
      orientation_manual = OrientationManual.create! valid_attributes
      delete orientation_manual_url(orientation_manual)
      expect(response).to redirect_to(orientation_manuals_url)
    end
  end
end
