require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/vehicle_types", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # VehicleType. As you add validations to VehicleType, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      VehicleType.create! valid_attributes
      get vehicle_types_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      vehicle_type = VehicleType.create! valid_attributes
      get vehicle_type_url(vehicle_type)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_vehicle_type_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      vehicle_type = VehicleType.create! valid_attributes
      get edit_vehicle_type_url(vehicle_type)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new VehicleType" do
        expect {
          post vehicle_types_url, params: { vehicle_type: valid_attributes }
        }.to change(VehicleType, :count).by(1)
      end

      it "redirects to the created vehicle_type" do
        post vehicle_types_url, params: { vehicle_type: valid_attributes }
        expect(response).to redirect_to(vehicle_type_url(VehicleType.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new VehicleType" do
        expect {
          post vehicle_types_url, params: { vehicle_type: invalid_attributes }
        }.to change(VehicleType, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post vehicle_types_url, params: { vehicle_type: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested vehicle_type" do
        vehicle_type = VehicleType.create! valid_attributes
        patch vehicle_type_url(vehicle_type), params: { vehicle_type: new_attributes }
        vehicle_type.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the vehicle_type" do
        vehicle_type = VehicleType.create! valid_attributes
        patch vehicle_type_url(vehicle_type), params: { vehicle_type: new_attributes }
        vehicle_type.reload
        expect(response).to redirect_to(vehicle_type_url(vehicle_type))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        vehicle_type = VehicleType.create! valid_attributes
        patch vehicle_type_url(vehicle_type), params: { vehicle_type: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested vehicle_type" do
      vehicle_type = VehicleType.create! valid_attributes
      expect {
        delete vehicle_type_url(vehicle_type)
      }.to change(VehicleType, :count).by(-1)
    end

    it "redirects to the vehicle_types list" do
      vehicle_type = VehicleType.create! valid_attributes
      delete vehicle_type_url(vehicle_type)
      expect(response).to redirect_to(vehicle_types_url)
    end
  end
end
