datetime_now = DateTime.now
array = [
	{created_at: datetime_now, updated_at: datetime_now, name: 'AFEGANISTÃO' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'ACROTÍRI E DECELIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'ÁFRICA DO SUL' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'ALBÂNIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'ALEMANHA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'AMERICAN SAMOA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'ANDORRA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'ANGOLA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'ANGUILLA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'ANTÍGUA E BARBUDA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'ANTILHAS NEERLANDESAS' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'ARÁBIA SAUDITA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'ARGÉLIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'ARGENTINA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'ARMÉNIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'ARUBA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'AUSTRÁLIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'ÁUSTRIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'AZERBAIJÃO' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'BAHAMAS' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'BANGLADECHE' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'BARBADOS' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'BARÉM' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'BASSAS DA ÍNDIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'BÉLGICA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'BELIZE' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'BENIM' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'BERMUDAS' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'BIELORRÚSSIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'BOLÍVIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'BÓSNIA E HERZEGOVINA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'BOTSUANA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'BRASIL' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'BRUNEI DARUSSALAM' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'BULGÁRIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'BURQUINA FASO' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'BURUNDI' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'BUTÃO' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'CABO VERDE' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'CAMARÕES' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'CAMBOJA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'CANADÁ' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'CATAR' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'CAZAQUISTÃO' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'CENTRO-AFRICANA REPÚBLICA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'CHADE' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'CHILE' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'CHINA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'CHIPRE' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'COLÔMBIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'COMORES' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'CONGO' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'CONGO REPÚBLICA DEMOCRÁTICA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'COREIA DO NORTE' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'COREIA DO SUL' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'COSTA DO MARFIM' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'COSTA RICA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'CROÁCIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'CUBA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'DINAMARCA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'DOMÍNICA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'EGIPTO' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'EMIRADOS ÁRABES UNIDOS' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'EQUADOR' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'ERITREIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'ESLOVÁQUIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'ESLOVÉNIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'ESPANHA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'ESTADOS UNIDOS' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'ESTÓNIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'ETIÓPIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'FAIXA DE GAZA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'FIJI' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'FILIPINAS' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'FINLÂNDIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'FRANÇA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'GABÃO' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'GÂMBIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'GANA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'GEÓRGIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'GIBRALTAR' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'GRANADA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'GRÉCIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'GRONELÂNDIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'GUADALUPE' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'GUAM' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'GUATEMALA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'GUERNSEY' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'GUIANA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'GUIANA FRANCESA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'GUINÉ' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'GUINÉ EQUATORIAL' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'GUINÉ-BISSAU' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'HAITI' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'HONDURAS' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'HONG KONG' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'HUNGRIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'IÉMEN' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'ILHA BOUVET' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'ILHA CHRISTMAS' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'ILHA DE CLIPPERTON' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'ILHA DE JOÃO DA NOVA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'ILHA DE MAN' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'ILHA DE NAVASSA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'ILHA EUROPA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'ILHA NORFOLK' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'ILHA TROMELIN' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'ILHAS ASHMORE E CARTIER' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'ILHAS CAIMAN' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'ILHAS COCOS { KEELING)' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'ILHAS COOK' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'ILHAS DO MAR DE CORAL' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'ILHAS FALKLANDS { ILHAS MALVINAS)' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'ILHAS FEROE' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'ILHAS GEÓRGIA DO SUL E SANDWICH DO SUL' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'ILHAS MARIANAS DO NORTE' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'ILHAS MARSHALL' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'ILHAS PARACEL' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'ILHAS PITCAIRN' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'ILHAS SALOMÃO' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'ILHAS SPRATLY' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'ILHAS VIRGENS AMERICANAS' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'ILHAS VIRGENS BRITÂNICAS' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'ÍNDIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'INDONÉSIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'IRÃO' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'IRAQUE' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'IRLANDA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'ISLÂNDIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'ISRAEL' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'ITÁLIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'JAMAICA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'JAN MAYEN' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'JAPÃO' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'JERSEY' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'JIBUTI' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'JORDÂNIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'KIRIBATI' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'KOWEIT' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'LAOS' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'LESOTO' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'LETÓNIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'LÍBANO' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'LIBÉRIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'LÍBIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'LISTENSTAINE' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'LITUÂNIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'LUXEMBURGO' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'MACAU' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'MACEDÓNIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'MADAGÁSCAR' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'MALÁSIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'MALAVI' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'MALDIVAS' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'MALI' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'MALTA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'MARROCOS' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'MARTINICA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'MAURÍCIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'MAURITÂNIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'MAYOTTE' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'MÉXICO' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'MIANMAR' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'MICRONÉSIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'MOÇAMBIQUE' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'MOLDÁVIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'MÓNACO' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'MONGÓLIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'MONTENEGRO' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'MONTSERRAT' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'NAMÍBIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'NAURU' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'NEPAL' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'NICARÁGUA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'NÍGER' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'NIGÉRIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'NIUE' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'NORUEGA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'NOVA CALEDÓNIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'NOVA ZELÂNDIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'OMÃ' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'PAÍSES BAIXOS' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'PALAU' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'PALESTINA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'PANAMÁ' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'PAPUÁSIA-NOVA GUINÉ' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'PAQUISTÃO' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'PARAGUAI' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'PERU' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'POLINÉSIA FRANCESA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'POLÓNIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'PORTO RICO' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'PORTUGAL' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'QUÉNIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'QUIRGUIZISTÃO' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'REINO UNIDO' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'REPÚBLICA CHECA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'REPÚBLICA DOMINICANA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'ROMÉNIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'RUANDA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'RÚSSIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'SAHARA OCCIDENTAL' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'SALVADOR' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'SAMOA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'SANTA HELENA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'SANTA LÚCIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'SANTA SÉ' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'SÃO CRISTÓVÃO E NEVES' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'SÃO MARINO' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'SÃO PEDRO E MIQUELÃO' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'SÃO TOMÉ E PRÍNCIPE' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'SÃO VICENTE E GRANADINAS' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'SEICHELES' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'SENEGAL' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'SERRA LEOA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'SÉRVIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'SINGAPURA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'SÍRIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'SOMÁLIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'SRI LANCA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'SUAZILÂNDIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'SUDÃO' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'SUÉCIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'SUÍÇA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'SURINAME' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'SVALBARD' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'TAILÂNDIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'TAIWAN' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'TAJIQUISTÃO' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'TANZÂNIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'TERRITÓRIO BRITÂNICO DO OCEANO ÍNDICO' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'TERRITÓRIO DAS ILHAS HEARD E MCDONALD' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'TIMOR-LESTE' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'TOGO' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'TOKELAU' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'TONGA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'TRINDADE E TOBAGO' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'TUNÍSIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'TURKS E CAICOS' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'TURQUEMENISTÃO' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'TURQUIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'TUVALU' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'UCRÂNIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'UGANDA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'URUGUAI' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'USBEQUISTÃO' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'VANUATU' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'VENEZUELA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'VIETNAME' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'WALLIS E FUTUNA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'ZÂMBIA' },
	{created_at: datetime_now, updated_at: datetime_now, name: 'ZIMBABUÉ' }
]

Country.insert_all(array)